services:
  timescaledb:
    image: timescale/timescaledb:2.11.0-pg14
    container_name: diablex_db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=diablex
    ports:
      - "5432:5432"
    volumes:
      - output_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    container_name: diablex_redis
    ports:
      - "6379:6379"

volumes:
  output_data:
